class DadosEstaticos {
 
  static obj(n,t) {
      return {nome: n, traducao: t, nErros: 0}
  }

  static lista_1() {
    return [
       this.obj("speech", "discurso"),
       this.obj("fountain", "fonte"),
       this.obj("stands", "fica"),
       this.obj("clap", "aplaudir"),
       this.obj("wand", "varinha"),
       this.obj("bridal", "nupcial"),
       this.obj("heed", "guarda"),
       this.obj("clown", "palhaço"),
       this.obj("baker", "padeiro"),
       this.obj("nurse", "enfermeira"),
       this.obj("eagle", "águia"),
       this.obj("goat", "cabra"),
       this.obj("island", "ilha"),
       this.obj("mall", "shopping"),
       this.obj("playground", "parque infantil"),
       this.obj("seashore", "beira mar"),
       this.obj("drum", "tambor"),
       this.obj("bed", "cama"),
       this.obj("blanket", "tapete"),
       this.obj("cot", "berço"),
       this.obj("kite", "pipa"),
       this.obj("rotten", "podre"),
       this.obj("granny", "avó"),
       this.obj("fire engine", "motor de fogo (motor a explosão)"),
       this.obj("lakes", "lagos"),
       this.obj("labor Day", "dia do trabalho"),
       this.obj("april fools day", "dia dos enganados (dia da mentira)"),
       this.obj("muddy", "turvo"),
       this.obj("scolded", "repreendeu"),
       this.obj("comb", "pente"),
       this.obj("van", "furgão"),
       this.obj("rainbow", "arco iris"),
       this.obj("bat", "bastão (ou morcego)"),
       this.obj("mug", "caneca"),
       this.obj("fan", "ventilador"),
       this.obj("broom", "vassoura"),
       this.obj("nest", "ninho"),
       this.obj("branch", "galho"),
       this.obj("handkerchief", "lenço"),
       this.obj("roof", "cobertura"),
       this.obj("hoof", "casco"),
       this.obj("ox", "boi"),
       this.obj("reindeer", "rena"),
       this.obj("pants", "calças"),
       this.obj("pajamas", "pijamas"),
       this.obj("shorts", "calção"),
       this.obj("trousers", "calças"),
       this.obj("scissors", "tesouras"),
       this.obj("sneakers", "tenis"),
       this.obj("slippers", "chinelos"),
       this.obj("stockings", "meias"),
       this.obj("crew", "equipe técnica"),
       this.obj("choir", "coro ('canção')"),
       this.obj("cattle", "gado"),
       this.obj("brood", "ninhada"),
       this.obj("the flight of steps", "o lance de escadas"),
       this.obj("bunch", "grupo (maço, punhado)"),
       this.obj("deck", " baralho"),
       this.obj("fleet", "frota"),
       this.obj("flock", "rebanho"),
       this.obj("gaggle", "bando (gansos)"),
       this.obj("herd", "rebanho"),
       this.obj("litter", "lixo"),
       this.obj("a litter of cubs", "uma ninhada de filhotes"),
       this.obj("a pod of whales", "um bando de baleias"),
       this.obj("a pack of wolves", "uma alcatéia de lobos"),
       this.obj("pride", "orgulho (também coletivo de leão)"),
       this.obj("stamps", "selos"),
       this.obj("swarm", "enxame (abelhas)"),
       this.obj("troupe", "trupe"),
       this.obj("bridegroom", "noivo"),
       this.obj("bride", "noiva"),
       this.obj("lioness", "leoa"),
       this.obj("waiter", "garçom"),
       this.obj("waitress", "garçonete"),
       this.obj("stewardess", "comissária de bordo (aeromoça)"),
       this.obj("steward", "mordomo"),
       this.obj("headmaster", "diretor"),
       this.obj("emperor", "emperador"),
       this.obj("actress", "atriz"),
       this.obj("empress", "emperatriz"),
       this.obj("mistress", "mestra"),
       this.obj("headmistress", "diretora"),
       this.obj("niece", "sobrinha"),
       this.obj("leverages", "aproveita"),
       this.obj("shall","deve"),
       this.obj("approach","abordagem"),
       this.obj("fortify","fortificar"), 
       this.obj("giant","gigante"),
       this.obj("step","degral"),
       this.obj("to step","dar um passo"),
       this.obj("blow","golpe"),
       this.obj("crush","paixão súbita"),
       this.obj("crush us","nos esmagar"),
       this.obj("armies","exército"),
       this.obj("treasure","tesouro"),
       this.obj("track","rastrear"),
       this.obj("ridge","cume"),
       this.obj("trial","tentatica"),
       this.obj("finisher","finalizador"),
       this.obj("approach of danger","aproximar do perigo"),
       this.obj("means","significa"),
       this.obj("whats means","quais meios"),
       this.obj("means of","meios de"),
       this.obj("means of transport","meios de tranporte"),
       this.obj("to step the ocenan","pisar no oceano"),
       this.obj("be our lot","ser nosso destino"),
       this.obj("ensure","garantir, assegurar"),
       this.obj("overseas", "no exterior"),
       this.obj("entered", "entrou"),
       this.obj("such", "tal"),
       this.obj("neither", "nem"),
       this.obj("nor", "nem"),
       this.obj("absence", "ausência"),
       this.obj("regarded", "considerdo"),
       this.obj("urge", "impulso"),
       this.obj("would", "seria"),
       this.obj("I would urge", "eu recomendo"),
       this.obj("flick", "folhear, estalito"),
       this.obj("to flick", " para apertar"),
       this.obj("sorts", "classifcar"),
       this.obj("ways", "caminhos"),
       this.obj("sorts ways", "tipos de maneiras"),
       this.obj("basis", "base"),
       this.obj("authority", "autoridade"),
       this.obj("headwords", "palavra chave"),
       this.obj("draw", "desenhar"),
       this.obj("draw atention", "chamar atenção"),
       this.obj("recongnize", "reconhecer"),
       this.obj("settled expression", "expressões estabelecidas"),
       this.obj("up-to-date", "atualizado"),
       this.obj("creep", "fluência, rasteijar,infiltram"),
       this.obj("quoted", "citados"),
       this.obj("significant", "significativo"),
       this.obj("bold face", "negrito"),
       this.obj("each others", "uns aos outros"),
       this.obj("stress", "estresse"),
       this.obj("to stress the importance", "para enfatizar a importância"),
       this.obj("commoner", "plebeu"),
       this.obj("commoner words", "palavras mais comuns"),
       this.obj("to pack", "empacotar"),
       this.obj("effort", "esforço"),
       this.obj("whose", "de quem"),
       this.obj("and many whose", "muito dos quais"),
       this.obj("although", "apesar"),
       this.obj("aimed", "destinada"),
       this.obj("would like", "gostaria"),
       this.obj("foremost", "acima de tudo"),
       this.obj("word-wide", "toda a palavra"),
       this.obj("wide", "larga"),
       this.obj("recorded", "gravada"),
       this.obj("sent", "enviei"),
       this.obj("meant", "significava"),
       this.obj("knowingly", "concientemente"),
       this.obj("unknowingly", "sem saber"),
       this.obj("typesetters", "tipógrafos"),
       this.obj("invaluable", "inestimável"),
       this.obj("elsewhere", "em outro lugar"),
       this.obj("publisher", "editora"),
       this.obj("tongue", "língua"),
       this.obj("taught", "ensinada"),
       this.obj("age", "idade"),
       this.obj("prizes", "prêmios"),
       this.obj("pastimes", "passatempos"),
       this.obj("sailing", "navegação"),
       this.obj("entertained", "entretida"),
       this.obj("round", "volta"),
       this.obj("graded", "graduada"),
       this.obj("carefully", "cuidadosamente"),
       this.obj("improve", "melhorar"),
       this.obj("confidence", "confiança"),
       this.obj("broaden", "ampliar"),
       this.obj("range", "alcance"),
       this.obj("mainly", "principalmente"),
       this.obj("textbooks", "livros didáticos"),
       this.obj("aim", "alvo"),
       this.obj("coverage", "cobertura"),
       this.obj("shift", "mudança"),
       this.obj("stretches", "alongar"),
       this.obj("pupils", "alunos"),
       this.obj("hearing", "audição"),
       this.obj("sustained", "sustentada"),
       this.obj("learners", "alunos"),
       this.obj("coursebooks", "livros didáticos"),
       this.obj("syllabuses", "currículos"),
       this.obj("generaly", "geralmente"),
       this.obj("summarize", "resumir"),
       this.obj("rewarding", "recompensador"),
       this.obj("directed", "dirigido"),
       this.obj("shape", "forma"),
       this.obj("flag", "bandeira"),
       this.obj("casualty", "acidente"),
       this.obj("bloodless", "sem sangue"),
       this.obj("bloodiest", "mais sangrento"),
       this.obj("rocked", "balançou"),
       this.obj("predicted", "previsto"),
       this.obj("until", "até"),
       this.obj("carry", "transportar"),
       this.obj("fartherland", "pátria"),
       this.obj("sparking", "faíscas"),
       this.obj("into sparking", "provocar"),
       this.obj("entirely", "enteiramente"),
       this.obj("so much", "muito"),
       this.obj("so that", "de modo a "),
       this.obj("crossroads", "encruzilhada"),
       this.obj("being", "ser"),
       this.obj("our", "nosso"),
       this.obj("landing", "aterrisagem"),
       this.obj("learnt", "apreendida"),
       this.obj("out in", "em"),
       this.obj("outlines", "contornos"),
       this.obj("assessment", "avaliação"),
       this.obj("clues", "pistas"),
       this.obj("afraid", "receosa"),
       this.obj("quite", "bastante"),
       this.obj("rhymes", "rimas"),
       this.obj("chants", "cantos (músicas)"),
       this.obj("recast", "reformulação"),
       this.obj("quiet", "quieta"),
       this.obj("sitting", "sentados"),
       this.obj("standing", "de pé"),
       this.obj("improvements", "melhorias"),
       this.obj("denoted", "denotada"),
       this.obj("benefit", "benefício"),
       this.obj("shy", "tímida"),
       this.obj("ashamed", "envergonhada"),
       this.obj("hesitate", "hesite"),
       this.obj("whole", "todo"),
       this.obj("likely", "provável"),
       this.obj("increases", "aumentar"),
       this.obj("spontaneous", "espontâneo"),
       this.obj("letting", "deixar, permitir"),
       this.obj("letting participants", "deixando os participantes"),
       this.obj("ranging", "variando"),
       this.obj("captivanting", "cativante"),
       this.obj("timeless", "eterna"),
       this.obj("statements", "afirmações"),
       this.obj("hurt", "machucar"),
       this.obj("aid", "ajuda"),
       this.obj("annoyed", "irritado"),
       this.obj("wealthy", "rico"),
       this.obj("steal", "roubar"),
       this.obj("fair", "justo"),
       this.obj("bow (arrow)", "arco (flexa)"),
       this.obj("outwitted", "despistou"),
       this.obj("hid", "esconder"),
       this.obj("trembing", "tremendo"),
       this.obj("known", "conhecido"),
       this.obj("reply", "resposta"),
       this.obj("curly", "encaracolado"),
       this.obj("forced", "forçada"),
       this.obj("agred", "concordar"),
       this.obj("unfair", "injusto"),
       this.obj("honoured", "honrado"),
       this.obj("blew", "explodiu"),
       this.obj("horn", "chifre (instrumento usado por caçadores)"),
       this.obj("hideout", "esconderijo"),
       this.obj("early", "cedo"),
       this.obj("happily", "alegremente"),
       this.obj("aloud", "em voz alta"),
       this.obj("joy", "alegria"),
       this.obj("embraced", "abraçou"),
       this.obj("fault", "falha"),
       this.obj("reacted", "reagiram"),
       this.obj("any more", "não mais"),
       this.obj("listen", "ouço"),
       this.obj("gallows", "forca"),
       this.obj("held", "mantido"),
       this.obj("crowd", "multidão"),
       this.obj("hungry", "com fome"),
       this.obj("sunset", "por do sol"),
       this.obj("trophy", "troféu"),
       this.obj("chased", "perseguido"),
       this.obj("rode", "montaram"),
       this.obj("sights", "vistas"),
       this.obj("blast", "explosão"),
       this.obj("market square", "praça do mercado"),
       this.obj("surrounded", "cercado"),
       this.obj("cut", "corte"),
       this.obj("almost", "quase"),
       this.obj("hangman", "carrasco"),
       this.obj("pity", "pena"),
       this.obj("deserve", "merecer"),
       this.obj("murderer", "assassino"),
       this.obj("till", "até"),
       this.obj("took", "tomou"),
       this.obj("lay", "deitar"),
       this.obj("dawn", "alvorecer"),
       this.obj("unconsicious", "inconciente"),
       this.obj("drooped", "caido"),
       this.obj("banged", "bateu"),
       this.obj("lifted", "levantado"),
       this.obj("appeared", "apareceu"),
       this.obj("luckily", "felizmente"),
       this.obj("fainted", "desmaiou"),
       this.obj("through", "através"),
       this.obj("meeting", "encontro"),
       this.obj("letting Allan", "deixando Allan"),
       this.obj("boring", "entediante"),
       this.obj("attend", "comparecer"),
       this.obj("indeed", "de fato"),
       this.obj("harm", "dano"),
       this.obj("monk", "moge"),
       this.obj("among", "entre"),
       this.obj("nearest", "mais próximo"),
       this.obj("even", "mesmo"),
       this.obj("sunrise", "nascer do sol"),
       this.obj("worse", "pior"),
       this.obj("just then", "só então"),
       this.obj("arrested", "preso"),
       this.obj("run", "correu"),
       this.obj("hit", "bateu"),
       this.obj("fell", "caiu"),
       this.obj("forgotten", "esquecidos"),
       this.obj("drank", "bebeu"),
       this.obj("dungeons", "masmorras"),
       this.obj("mercy", "misericórdia"),
       this.obj("hanged", "enforcado"),
       this.obj("traitor", "traidor"),
       this.obj("regiment", "regimento"),
       this.obj("caught", "pegou"),
       this.obj("delighted", "deleitado"),
       this.obj("enxange", "troca"),
       this.obj("youth", "juventude"),
       this.obj("elders", "anciãos"),
       this.obj("must", "devo"),
       this.obj("arm chair", "poltrona"),
       this.obj("instead", "ao inveś"),
       this.obj("notions", "noções"),
       this.obj("began", "começasse"),
       this.obj("greed", "ganância"),
       this.obj("ugly", "feio"),
       this.obj("wicked", "mal (perverso)"),
       this.obj("nowhere", "nenhum lugar"),
       this.obj("everyone", "todos"),
       this.obj("arranged", "organizado"),
       this.obj("wedding", "casamento"),
       this.obj("couple", "casal"),
       this.obj("moreover", "alem disto"),
       this.obj("meanwhile", "entretanto"),
       this.obj("happiest", "mais feliz"),
       this.obj("tenderly", "ternamente"),
       this.obj("shouting", "gritando"),
       this.obj("doubt", "dúvida"),
       this.obj("soon", "em breve"),
       this.obj("couple minutes", "alguns minutos"),
       this.obj("celeb", "celebridade"),
       this.obj("migth", "poderia"),
       this.obj("mustn't", "não deve"),
       this.obj("spelling", "soletração"),
       this.obj("awesome", "impressionante")
    ];
  }
}
